# Funding options for Ralph AI
# Uncomment and add your funding platforms when ready

# github: [fantomx42]
# patreon: username
# open_collective: ralph-ai
# ko_fi: username
# custom: ["https://ralph-ai.org/donate", "https://buymeacoffee.com/username"]
