name: Feature Request
description: Suggest a new feature or enhancement for Ralph AI
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Which component would this affect?
      options:
        - Translator Agent
        - Orchestrator Agent
        - Engineer Agent
        - Designer Agent
        - ASIC System
        - Message Bus
        - Memory/Vector DB
        - Web UI
        - Voice Interface
        - Vision Module
        - Docker Sandbox
        - New Component
        - Multiple Components
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: Have you thought of other ways to solve this?

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide examples of how this feature would be used
      placeholder: |
        1. User wants to...
        2. System would...
        3. Result would be...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas on how to implement this?
      placeholder: Optional technical suggestions

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to implement this feature and submit a PR
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been requested
          required: true
        - label: This feature aligns with Ralph AI's core philosophy (autonomous iteration)
          required: true
